image: python:3.10

cache:
  paths:
    - .venv

stages:
  - style
  - test

before_script:
  - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - chmod 400 "$SSH_PRIVATE_KEY"
  - ssh-add "$SSH_PRIVATE_KEY"
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "Cloning submodules..."
  - git submodule init
  - git submodule update --recursive
  - echo "Submodules initialized."
  - pip install --upgrade pip
  - pip install poetry
  - poetry config virtualenvs.in-project true
  - poetry install --with test
  - source .venv/bin/activate

black:
  stage: style
  needs: []
  image: pyfound/black:24.1.1 
  before_script: []
  cache: []
  allow_failure: true
  script:
    - black --check --verbose --diff --color drplanner
    - black --check --verbose --diff --color tests

unittest:
  stage: test
  script:
    - coverage run --source=./drplanner -m unittest discover tests
    - coverage report -m || true
    - coverage xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
