image: python:3.10

cache:
  paths:
    - .venv

stages:
  - style
  - test

before_script:
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - mkdir -p ~/.ssh
  - touch ~/.ssh/id_rsa
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host *\nStrictHostKeyChecking no\n" > ~/.ssh/config
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_rsa
  - echo "Cloning submodules..."
  - git submodule init
  - git submodule update --recursive
  - echo "Submodules initialized."
  - pip install --upgrade pip
  - pip install poetry
  - poetry config virtualenvs.in-project true
  - poetry install --with test
  - source .venv/bin/activate

black:
  stage: style
  needs: []
  image: pyfound/black:24.1.1 
  before_script: []
  cache: []
  allow_failure: true
  script:
    - black --check --verbose --diff --color drplanner
    - black --check --verbose --diff --color tests

unittest:
  stage: test
  script:
    - coverage run --source=./drplanner -m unittest discover tests
    - coverage report -m || true
    - coverage xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
